"""AI-OS Reproducible Execution Plane V1 — additive task-engine substrate."""

from __future__ import annotations

EXECUTION_BUNDLE_VERSION = 1
EXECUTION_PROTOCOL_VERSION = "1.1"
SUPPORTED_EXECUTION_PROTOCOL_VERSIONS = frozenset({"1.1"})
PROOF_BUNDLE_VERSION = 2
LEASE_TTL_SECONDS = 4 * 60 * 60
EXECUTION_MODES = frozenset({"TEST", "BENCHMARK", "REPLAY", "PROOF", "MUTATE", "LIVE_READ_ONLY"})
# Back-compat alias; prefer EXECUTION_MODES / PLANE_REQUIRED_MODES in new code.
WRITE_MODES = EXECUTION_MODES
PLANE_REQUIRED_MODES = EXECUTION_MODES
ISOLATED_WRITE_MODES = frozenset({"TEST", "BENCHMARK", "REPLAY", "PROOF", "MUTATE"})
LIVE_READ_MODES = frozenset({"LIVE_READ_ONLY"})
LEGACY_EXECUTION_MODES = frozenset({"DOCS", "STATIC", "READ_ONLY_LOCAL"})
FAIL_CLOSED_WRITE_MODES = ISOLATED_WRITE_MODES
CAPABILITY_PROFILES = frozenset({"NO_EXTERNAL", "DECLARED_LLM", "LIVE_READ_ONLY"})
SEED_ORIGINS = frozenset({"EMPTY", "FIXTURE", "SNAPSHOT", "HISTORICAL_REPLAY"})
GRAPH_STATUSES = frozenset({"CURRENT", "STALE_ADVISORY", "UNAVAILABLE"})
LIFECYCLE_STATES = frozenset({"ACTIVE", "CLOSED_RETAINED", "DESTROYABLE", "DESTROYED"})
MUTATION_MODES = frozenset({"MUTATE", "READ_ONLY", "LEGACY"})
